2.1 numpy基础知识  numpy 在实际的使用中，加深理解 kaggle比赛

In [2]:
import numpy as np

In [3]:
# 普通数组
array = [[1,2,3],[2,3,4]]

In [4]:
# np数组
np_array = np.array([[1,2,3],[2,3,4]])

打印两种不同的array

In [5]:
print(array)
print(np_array)

[[1, 2, 3], [2, 3, 4]]
[[1 2 3]
 [2 3 4]]


In [6]:
print('dim,shape,size',np_array.ndim,np_array.shape,np_array.size)

dim,shape,size 2 (2, 3) 6


2.2 numpy创建数组

In [18]:
import numpy as np

In [19]:
# np.int ...
# np.float....  16 32 63...
a = np.array([2,23,4],dtype=np.int64)
b = [2,23,4]
print(a.dtype)
#  np 数组在内部没有逗号
print(a) 
# 链表有逗号
print(b)

int64
[ 2 23  4]
[2, 23, 4]


In [20]:
 a = np.array([[2,23,4],[2,23,4]])
print(a)

[[ 2 23  4]
 [ 2 23  4]]


In [21]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
print(np.ones((3,4)))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
print(np.empty((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#  利用一个范围内的数字 重构得到矩阵
a = np.arange(12)
print(a)

In [32]:
b = a.reshape((3,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


产生线段

In [46]:
a = np.linspace(1,10,6)
# 包含6个数字
print(a)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [47]:
a.reshape((2,3))

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

2.3 numpy的基础运算

In [49]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)

In [51]:
c = a - b
print(a,b)
print(c)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]


In [52]:
c = a + b
print(a,b)
print(c)

[10 20 30 40] [0 1 2 3]
[10 21 32 43]


In [53]:
# 逐个的相乘
c = a * b
print(a,b)
print(c)

[10 20 30 40] [0 1 2 3]
[  0  20  60 120]


python 中的平方

In [54]:
c = b**2
print(c)

[0 1 4 9]


三角函数运算

In [55]:
c = 10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


快捷运算

In [56]:
print(b)
print(b>3)
print(b==3)

[0 1 2 3]
[False False False False]
[False False False  True]


矩阵的运算

In [58]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))

包含有两种乘法  对应位置相乘  矩阵相乘

In [64]:
c = a*b
c_dot = np.dot(a,b)
c_dot2 = a.dot(b)
print(a)
print(b)
print(c)
print(c_dot)
print(c_dot2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


产生随机的array

In [67]:
import numpy as np
a = np.random.random((2,4))
print(a)

[[0.65758039 0.97997468 0.12346909 0.05855168]
 [0.90359947 0.60814188 0.89771982 0.53743916]]


In [68]:
# 最值  和
print(np.max(a))
print(np.max(a))
print(np.sum(a))

0.9799746841238087
0.9799746841238087
4.766476163585429


In [72]:
#  不同维度的最值 axis
# 列数
print(np.max(a,axis =0)) 
# 行数
print(np.max(a,axis =1))

[0.90359947 0.97997468 0.89771982 0.53743916]
[0.97997468 0.90359947]


 2.4 numpy 基础运算2

In [75]:
import numpy as np
A = np.arange(2,14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [78]:
# 拿到最值的索引
print(np.argmin(A))

0


In [86]:
# 快捷方法 median 中位数  均值 mean
print(np.mean(A))
print(np.average(A))
print(A.mean())
# print(A.average)  报错 没有这个方法

7.5
7.5
7.5


前缀和  累差 非零

In [92]:
print(A)
print(np.cumsum(A))
print(np.diff(A))
# 输出不是零的数的行列值
print(np.nonzero(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [94]:
print(np.sort(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [95]:
# 矩阵 转置
print(A)
B = np.transpose(A)
C = A.T
print(B)
print(C)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


矩阵$A^T * A$

In [97]:
print(A.dot(A.T))


[[ 54 110 166]
 [110 230 350]
 [166 350 534]]


In [99]:
#  clip 用的时候查看结果即可
print(A)
print(np.clip(A,5,9))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


2.5 numpy的索引

In [111]:
import numpy as np
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2])
print(A[:][2])
print(A[2][:])
print(A[:][:])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
[11 12 13 14]
[11 12 13 14]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [121]:
# 打印出对应行
print(A[2,:])
print(A[2])
# 打印出对应列
print(A[:,1])

SyntaxError: invalid syntax (<ipython-input-121-e6ceb7bf638c>, line 7)

In [127]:
print(A)
print(A[2][1])
print(A[2,1])
print(A[2,1:2])
print(A[2:3,1])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
12
[12]
[12]


In [128]:
# 默认存在行迭代  列的迭代可以转置来实现
for row in A:
    print(row)
for col in A.T:
    print(col)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [143]:
# 迭代打印所有的值
# 转换为一维  
#  A.flatten()  返回的是一个改变了形状的array   A.flat 一个迭代器
for item in A.flat:
    #     不带方括号
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [142]:
B = A.reshape(12,1)
# 带有方括号 所以还是矩阵 需要进一步转换
for i in range(B.size):
    print(B[i])

[3]
[4]
int32
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]


2.6 numpy的array合并

按行

In [145]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))    # vertical stack

[[1 1 1]
 [2 2 2]]


按列 vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作。

In [146]:
C = np.vstack((A,B))      
print(A.shape,C.shape)

(3,) (2, 3)


利用shape函数可以让我们很容易地知道A和C的属性，从打印出的结果来看，A仅仅是一个拥有3项元素的数组（数列），而合并后得到的C是一个2行3列的矩阵。

np.hstack() 

In [147]:
D = np.hstack((A,B))       # horizontal stack
print(D)
print(A.shape,D.shape)

[1 1 1 2 2 2]
(3,) (6,)


D本身来源于A，B两个数列的左右合并，而且新生成的D本身也是一个含有6项元素的序列

np.newaxis()

转置操作，如果面对如同前文所述的A序列， 转置操作便很有可能无法对其进行转置（因为A并不是矩阵的属性），此时就需要我们借助其他的函数操作进行转置

In [150]:
# 序列转换为矩阵
print(A[np.newaxis,:])
print(A[np.newaxis,:].shape)
print(A[:,np.newaxis])

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]


In [151]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

In [153]:
C = np.vstack((A,B))   
D = np.hstack((A,B)) 
print(D)

[[1 2]
 [1 2]
 [1 2]]


np.concatenate()

合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便。axis参数很好的控制了矩阵的纵向或是横向打印，相比较vstack和hstack函数显得更加方便。D = np.concatenate((A,B),axis=1)

In [154]:
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [156]:
D = np.concatenate((A,B,B,A),axis=1)
print(D)

[[1 2]
 [1 2]
 [1 2]]


2.7 Numpy array 分割

In [157]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.split()

纵向分割

In [158]:
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


横向分割

In [159]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


错误的分割 范例的Array只有4列，只能等量对分，因此输入以上程序代码后Python就会报错

In [161]:
# print(np.split(A, 3, axis=1))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


np.array_split()

不等量的分割 在机器学习时经常会需要将数据做不等量的分割，因此解决办法为np.array_split()

In [162]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


其他的分割方式,在Numpy里还有np.vsplit()与横np.hsplit()方式可用。

In [163]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


2.8 Numpy copy & deep copy

In [164]:
import numpy as np
a = np.arange(4)
b = a
c = a
d = b

‘=’赋值

In [167]:
# 改变a的第一个值，b、c、d的第一个值也会同时改变
a[0] = 11
print(a)
print(b)

[11  1  2  3]
[11  1  2  3]


In [169]:
# 确认b、c、d是否与a相同。
b is a  # True
c is a  # True
d is a  # True

True

In [171]:
# 同样更改d的值，a、b、c也会改变。
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)   

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


copy()复制 的赋值方式没有关联性
此时a与b已经没有关联

In [172]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
